// APP REDUCER
export const SET_APP_INFO = "SET_VALUE_HOOK";
export const SET_MENUS = "SET_MENUS";

// PAGE REDUCER
export const TOGGLE_TABLE_LOADING = "TOGGLE_TABLE_LOADING";
export const TOGGLE_FORM_LOADING = "TOGGLE_FORM_LOADING";
export const SET_DEFAULT_STATE = "SET_DEFAULT_STATE";
export const SET_FORM_FIELD = "SET_FORM_FIELD";
export const SET_BULK_FORM_FIELD = "SET_BULK_FORM_FIELD";
export const SET_LIST = "SET_LIST";
export const SET_FORM_FIELD_UPDATE = "SET_FORM_FIELD_UPDATE";
